#!/bin/bash
echo "1. Set lxappearance theme"
echo "2. Configure wifi"
echo "3. Install i3-gaps"
echo "4. Configure Firefox"
echo "- Setup Firefox Secure Profile: https://ffprofile.com/"
echo "- Install BitWarden extension: https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/"
echo "- Install Decentraleyes extension: https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/"
echo "- Install Ublock Origin extension: https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/"
echo "Open URLs in Kitty: Ctrl+Shift+e"
