#!/bin/bash
echo "1. Configure wifi"
echo "2. Set lxappearance theme"
echo "3. Configure Firefox"
echo "- Setup Firefox Secure Profile: https://ffprofile.com/"
echo "- Install BitWarden extension: https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/"
echo "- Install Decentraleyes extension: https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/"
echo "- Install Ublock Origin extension: https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/"
echo "- Install Dracula theme extension: https://addons.mozilla.org/en-US/firefox/addon/dracula-dark-colorscheme/"
echo "Open URLs in Kitty: Ctrl+Shift+e"
echo "4. Install CLion"
echo "5. Install Pycharm"
echo "6. Install Tor"
echo "7. Install yt-dlp"
