#+TITLE:debian-autosetup

A simple bash script (compatible with Debian-based distributions) to install software and configure your dotfiles after a fresh install.

This script is capable of installing:
- Debian sources
- Apt packages
- Flatpak/Flathub packages
- Fonts
- Git Repositories
- GTK themes
- Dotfiles managed with git --bare repositories

* Usage
#+BEGIN_SRC :tangle no
  git clone https://github.com/not-tacit/debian-autosetup
  cd debian-autosetup
  chmod +x install.sh
  ./install.sh
#+END_SRC

* Customizatoin
By default, the script is setup to my configuration but is modular and easily customizable.

- Just modify the lists with your requirements and they will be installed.
- Some actions like additional processing of git repositories after download may require custom scripting. 

* Debian Sources
#+BEGIN_SRC sh :tangle install.sh :shebang "#!/bin/bash"
  debian_sources=(
      contrib
      non-free
  )
#+END_SRC

* Apt Packages
#+BEGIN_SRC sh :tangle install.sh
  apt_package_sources=(
      # gui
      xorg
      i3-wm
      dunst
      rofi
      polybar
      picom
      nitrogen
      lxappearance
      # utilities/tools
      pulseaudio
      network-manager
      network-manager-gnome
      kitty
      unzip
      # editors
      emacs
      vim
      # programs
      firefox-esr
      anki
      # media
      ranger
      sxiv
      zathura
      vlc
      # other
      flatpak
      # drivers
      firmware-iwlwifi
      linux-headers-amd64
      nvidia-driver
      firmware-misc-nonfree
  )
#+END_SRC

* Flatpak/Flathub Packages
#+BEGIN_SRC sh :tangle install.sh
  flatpak_package_list(
      # discord
      com.discordapp.Discord
      # spotify
      com.spotify.Client
  )
#+END_SRC

* Font Sources
#+BEGIN_SRC sh :tangle install.sh
  font_sources=(
      # Fira Code
      https://github.com/tonsky/FiraCode/releases/download/6.2/Fira_Code_v6.2.zip
      # Font Awesome 5
      https://github.com/FortAwesome/Font-Awesome/releases/download/5.15.4/fontawesome-free-5.15.4-desktop.zip
  )
#+END_SRC

* Git Sources
I use git to source my theme and i3-gaps for debian. The installer can clone any repo into ~/Downloads. It is up to you to process the downloaded content yourself.
#+BEGIN_SRC sh :tangle install.sh
  git_sources=(
      # gtk - dracula theme - other theming done in configs themselves
      https://github.com/dracula/gtk
      # i3-gaps debian
      https://github.com/maestrogerardo/i3-gaps-deb
  )
  #+END_SRC

* Install

* Dotfiles
